github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "github.com/paketo-buildpacks/libjvm/cmd/helper"

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/adoptium","gcr.io/paketo-buildpacks/adoptium"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[8,9)"
- name:            JRE 8
  id:              jre
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[8,9)"
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[11,12)"
- name:            JRE 11
  id:              jre
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[11,12)"
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[17,18)"
- name:            JRE 17
  id:              jre
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[17,18)"
- name:            JDK 21
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[21,22)"
- name:            JRE 21
  id:              jre
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[21,22)"
- name:            JDK 23
  id:              jdk
  version_pattern: "23\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[23,24)"
- name:            JRE 23
  id:              jre
  version_pattern: "23\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[23,24)"

# ARM64
- name:            JDK 8 ARM64
  id:              jdk
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[8,9)"
    arch: "arm64"
- name:            JRE 8 ARM64
  id:              jre
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[8,9)"
    arch: "arm64"
- name:            JDK 11 ARM64
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[11,12)"
    arch: "arm64"
- name:            JRE 11 ARM64
  id:              jre
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[11,12)"
    arch: "arm64"
- name:            JDK 17 ARM64
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[17,18)"
    arch: "arm64"
- name:            JRE 17 ARM64
  id:              jre
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[17,18)"
    arch: "arm64"
- name:            JDK 21 ARM64
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[21,22)"
    arch: "arm64"
- name:            JRE 21 ARM64
  id:              jre
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[21,22)"
    arch: "arm64"
- name:            JDK 23 ARM64
  id:              jdk
  version_pattern: "23\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jdk
    version:        "[23,24)"
    arch: "arm64"
- name:            JRE 23 ARM64
  id:              jre
  version_pattern: "23\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/adoptium-dependency:main
  with:
    implementation: hotspot
    type:           jre
    version:        "[23,24)"
    arch: "arm64"